### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/beaker-infrastructure#39]
```
curl https://beaker-project.org -v
* Host beaker-project.org:443 was resolved.
* IPv6: 2620:52:3:1:5054:ff:feeb:fe89
* IPv4: 8.43.85.221
*   Trying [2620:52:3:1:5054:ff:feeb:fe89]:443...
* Connected to beaker-project.org (2620:52:3:1:5054:ff:feeb:fe89) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* SSL certificate problem: certificate has expired
* Closing connection
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

@duck-rh can you look into it?

**Comment by mscherer** [comment]
disk was full. I cleaned up, and it should be fixed in the next hour.

**Comment by duck-rh** [comment]
Thanks @mscherer 

I checked and certbot is doing fine now and the cert was properly renewed. Nos space problem remains.646980
